### ISSUE TITLE
cert file link is incorrect on http, file does not exist

### ISSUE THREAD

**Issue by ghost** [me-box/databox#248]
After running databox the non SSl site's "download certificate" link doesnt resolve, points to a file that deosn't exist. Should probably point to rootCert.pem but points to something else.

**Comment by Toshbrown** [comment]
It was fixed in this https://github.com/me-box/core-container-manager/commit/aa6af0e3a1df7b9f36d40bce14bee506127c881a

Its version 0.3.2 still has this bug, you can test the fix by running `./start-databox latest`

This fix will be included in the next release.

**Comment by pooyadav** [comment]
I found this is still an issue. I have installed the certificate, but still databox UI doesn't find it when running as non-ssl site.
